// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarNJupV_P6b3gSEJwuY5djm01PaiTT30',
    appId: '1:364411832758:web:7abf6ac799697b38d9d917',
    messagingSenderId: '364411832758',
    projectId: 'epayroll-2e175',
    authDomain: 'epayroll-2e175.firebaseapp.com',
    storageBucket: 'epayroll-2e175.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8ZEKSav5cbYKA-orxwbp2rSLgWkmm44',
    appId: '1:364411832758:android:f086b269d9d3ba60d9d917',
    messagingSenderId: '364411832758',
    projectId: 'epayroll-2e175',
    storageBucket: 'epayroll-2e175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvZ1SRRegalVwggcOUog0aeiyylB3SWc',
    appId: '1:364411832758:ios:d83d39d3bf4ba354d9d917',
    messagingSenderId: '364411832758',
    projectId: 'epayroll-2e175',
    storageBucket: 'epayroll-2e175.appspot.com',
    iosClientId: '364411832758-rq26kicc2sasc61pmufdij93kv2q2jic.apps.googleusercontent.com',
    iosBundleId: 'com.example.payroll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYvZ1SRRegalVwggcOUog0aeiyylB3SWc',
    appId: '1:364411832758:ios:d83d39d3bf4ba354d9d917',
    messagingSenderId: '364411832758',
    projectId: 'epayroll-2e175',
    storageBucket: 'epayroll-2e175.appspot.com',
    iosClientId: '364411832758-rq26kicc2sasc61pmufdij93kv2q2jic.apps.googleusercontent.com',
    iosBundleId: 'com.example.payroll',
  );
}
